### ISSUE TITLE
Matching Postcodes With Google

### ISSUE THREAD

**Issue by HockeyJustin** [ideal-postcodes/postcodes.io#103]
Hi,

I'm looking at using postcodes.io, which looks great. Just doing my own validation. 

If I take a postcode e.g. a [Tesco](https://www.tesco.com/store-locator/uk/?bID=2348) in Croydon (CR0 7ER) and look it up on Google, I get a url that includes the Lat/Long like [https://www.google.co.uk/maps/search/23+Shirley+Rd,+Croydon+CR0+7ER/@51.382061,-0.0655232,17z/data=!3m1!4b1](https://www.google.co.uk/maps/search/23+Shirley+Rd,+Croydon+CR0+7ER/@51.382061,-0.0655232,17z/data=!3m1!4b1).

If i take the lat/long from that and put it into postcodes.io e.g. [https://api.postcodes.io/postcodes?lon=-0.0655232&lat=51.382061&radius=200](https://api.postcodes.io/postcodes?lon=-0.0655232&lat=51.382061&radius=200), I don't get that postcode back. Oddly, it is inlcluded for some postcodes, but not others.

My aims are to:

1. Get the exact postcode for the coordinates (if adding a small radius e.g. 1-10)
2. Get a list of nearby postcodes including the exact match (as shown above)

Is there something wrong with my method here?

**Comment by mtmail** [comment]
I'd say the coordinates in Google Map's URL are misleading. When I search from Germany I get yet another coordinate pair in the URL. Maybe related to screen size https://www.google.de/maps/place/Shirley+Rd,+Croydon+CR0+7ER,+Vereinigtes+Königreich/@51.383237,-0.0665689,17z

If you replace -0.065 with -0.062 it's the first match. https://api.postcodes.io/postcodes?lon=-0.0625&lat=51.382&radius=200

**Comment by StevenWillett** [comment]
So these are my findings:
CR0 7ER = @51.383237,-0.0665689
Tesco Express = @51.3820915,-0.0653747

The more digits = a more accurate result, 
A postcode however will always be more vague than long / lat.

Maybe try the geocoding API for a more accurate result.
https://developers.google.com/maps/documentation/geocoding/intro

**Comment by cblanc** [comment]
Hi there,

The above comments are feasible workarounds. In this particular instance, you're not seeing CR0 7ER it's because the entire result set is 16 postcodes and the Tesco postcode is furthest (198m from the specified geolocation). You may increase the limit with `limit=` or `l=`. Also, limit is capped at 100 (default is 10)

```
https://api.postcodes.io/postcodes?lon=-0.0655232&lat=51.382061&radius=200&limit=20
```

You might find it a bit problematic to find matching postcodes using a small search radius with Google's and ONS' dataset. As demonstrated by your example they can diverge by a couple hundred metres or so

As mentioned above, best thing to do is validate with a postcode (if possible) and then, if required, do a sanity check of the distance - a simple haversine distance computation would probably suffice. You can find nearest postcodes using location search using either ONS or Google's geolocation information

**Comment by HockeyJustin** [comment]
@cblanc - Thanks for the response.

I would expect the big corp to be accurate, but it seems @mtmail is right. If I take that set of Coordinates from google and plug them in separately, they go to a different address!

I tried your values vs the ones that come up in the google search as a [directions](https://www.google.co.uk/maps/dir/51.3815965941136,+-0.0627768632844159/51.383237,-0.0665689/@51.3825752,-0.0657966,18z/data=!3m1!4b1!4m6!4m5!1m3!2m2!1d-0.0627769!2d51.3815966!1m0) a - b to see who was right - it was your location!

Sorry to have bothered you and thank you for the quick response.

As a point to note. If I use the HTML5 location api [e.g this site](https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_geolocation) , I still need to add a bit of wiggle room (100m) on the radius, but it's good enough for my needs.

Thanks for your help.
