### ISSUE TITLE
admin_county not always populated

### ISSUE THREAD

**Issue by DTHyphen8** [ideal-postcodes/postcodes.io#1076]
I've found some requests aren't returning admin_county. The default examples on https://postcodes.io only return it for the Oxfordshire example. I would expect to see "Greater Manchester", and "Tyne and Wear" for the following examples.

**Comment by cblanc** [comment]
Indeed. These are administrative counties which only cover a small portion of the *England*. I'm afraid there's no good (= maintained + generally agreed upon) list of counties in the UK. The one available in ONSPD is one of two which is actively maintained because it's in active use. There's another called non-metropolitan counties but that comes with another set of problems (not generally agreed upon delineations)
