### ISSUE TITLE
Document the files in the data directory

### ISSUE THREAD

**Issue by MarkMaldaba** [ideal-postcodes/postcodes.io#132]
It would be really useful if there was some documentation about the files in the data directory, and what they contain.  Also, the source of the data would be a useful thing to provide, too.

In particular, I notice that ````ccgs.js```` contains about 40,000 records!  That's a bit of a surprise, considering there are only about 200 CCGs.  What is all the other data in this file?

The other thing that would be really useful to know is whether these files contain historical data or whether they only contain current values.  For example, if two CCGs merged, would we expect to see 3 records in the file (the 2 old CCGs and the new one) or just 1 (the new one only).

The purpose behind my questions is to find out whether we can use these to provide appropriate list data in our application, for situations where postcode lookup is unavailable, or gives inappropriate results (for example, if someone is registered at a GP near their work rather than near their home).

**Comment by cblanc** [comment]
Hi Mark. I'll take a look at documenting this for the next release. In the meantime I can give you a quick overview of how new data is appended to `data/*.json` at each quarterly updated

The JSON files are key-value representations of GSS codes and their associated names. The vast majority of the seed data came from the `.txt` and `.xls` files accompanying the ONSPD dataset

The process of updating data files for every data release is a rather painstaking  process and difficult to automate for the time being.  For every new release, this involves:
1) Scanning each line of a new ONSPD file and comparing it with the `data/*.json` files. This typically generates thousands of codes to add each quarter
2) For each missing code, ~40-50 `.txt` files provided alongside ONSPD are scanned for their relevant names. Unfortunately, this can be quite tricky as these files aren't always helpfully named and have different schemas
3) Based on the file schema, I'll write a script to extract the code and name and merge it into the relevant JSON data file
4) Even after steps 2 & 3, there are also potentially thousands of new codes which are in the ONSPD datafile but not in the accompanying codes dataset. Often it's just because these code datasets are a few months behind ONSPD. In this instance, I would also consult external, more up-to-date sources and write additional scripts to download, parse and merge those codes as well

One more thing to note is that these JSON files are effectively "append only". This may be why there are ~40,000 LSOA codes alongside the 200 CCG codes in the CCG file. My understanding is that CCGs are based from LSOAs. It may have been that earlier incarnations of ONSPD was reporting LSOA codes for some postcodes in lieu of CCG codes (possibly for the non-English postcodes). It's difficult to check at this time because I'm not able to find an ONSPD older than 2016

I've been reticent to go back and delete unused codes primarily because it would not save space (as git will dutifully keep the data in the commit history). However, based on your feedback, it may be worth going back to prune the data that's there.

To answer your question regarding historical data, you should see all 3 CCGs . If a new CCG is created by merger, my understanding is a new GSS code would be created and the related postcodes would be updated to point at the new GSS code. As mentioned, the older CCG codes have not been purged from `ccgs.json`, the most recent/relevant ones should be at the bottom of the file. You can verify this [here](https://github.com/ideal-postcodes/postcodes.io/commits/master/data/ccgs.json)

**Comment by MarkMaldaba** [comment]
Hi @cblanc - thanks for you very quick and helpful reply.

It sounds like updating is quite a pain!  Are ONSPD aware of the reusability issues in their distribution methods?  Given that the whole point of this is to make the data publicly available they might be receptive to feedback about how to provide it in a more easily consumable format.

In terms of the data files, assuming the data set continues to function as you describe (i.e. that old values are not removed) I wonder how much work it would be to add an 'is current' column.  That would be useful for a good number of downstream users, I'm sure, even if it isn't directly required for postcodes.io (which, I assume, purely uses the files to give the correct labels to the GSS codes in the main postcode data set).  If it is not much extra work it would definitely be of great benefit.

Either way, keep up the good work, and I look forward to the documentation in the next release.

- Mark
