### ISSUE TITLE
CCG Boundaries?

### ISSUE THREAD

**Issue by willwade** [ideal-postcodes/postcodes.io#160]
Are the CCG codes correct? 

I ask because doing a search on CA72PG says the address is in "ccg": "NHS North Cumbria" however - according to this latest data set http://geoportal.statistics.gov.uk/datasets/clinical-commissioning-groups-april-2017-generalised-clipped-boundaries-in-england-v4?geometry=-14.711%2C50.684%2C10.755%2C55.307 - there is only NHS Cumbria.

**Comment by cblanc** [comment]
Hi Will, thanks for raising this issue. Had a good look at the data just to double check the extraction was working as expected

The CCG code/name extraction script can be found here: https://github.com/ideal-postcodes/postcodes.io/blob/master/data/scripts/ccgs.js

At the moment it consumes `CCG names and codes UK as at 04_17.txt` provided by the ONSPD dataset. Here's the corresponding line in the CCG dataset:

```
./CCG names and codes UK as at 04_17.txt:204:E38000215	01H	NHS North Cumbria CCG
```

Furthermore, here is the line that details `CA7 2PG` from the ONSPD main datafile. You'll find `E38000215` somewhere in there 

```
"CA7 2PG","CA7  2PG","CA7 2PG","200006","","E10000006","E07000026","E05003138","0","311213","0541709","1","E18000002","E19000001","E92000001","E12000002","1","E14001053","E15000002","E24000021","E30000290","E16000086","E05003138","16UBGF03","FEGF03","1","Q13","909","QDK","17FEGF","16UBGF","16UBGF","16UBHN","E00096682","16UBHN","E99999999","E01019128","E02003967","3","3A1","5D4","E00096682","E01019128","E02003967","E04002410","E33007761","E38000215","E34003607","E35999999","E2","1B1",54.762436,-3.381365,"E37000007","","E23000002",14044
```

I think that both the postcode and CCG data was parsed correctly. We're also due to deploy the Nov 2017 dataset next week and its the same story (CA7 2PG -> E38000215 -> NHS North Cumbria CCG)

I had a look at the Cumbria CCG website and it seems that this CCG no longer exists. It was split in 2 in April:

```
CCGs in Cumbria changed boundaries in April 2017 to create two organisations: North Cumbria CCG and Morecambe Bay CCG
``` 

There's a little more information [here](https://www.cumbriapartnership.nhs.uk/news/new-boundaries-for-ccgs-in-north-lancashire-and-cumbria-are-confirmed-for-2#sthash.fPuxaJ5z.dpbs)

My guess is the data gathered in http://geoportal.statistics.gov.uk/datasets/clinical-commissioning-groups-april-2017-generalised-clipped-boundaries-in-england-v4?geometry=-14.711%2C50.684%2C10.755%2C55.307 may be on the wrong side of the April 2017 boundary change and is slightly stale

**Comment by willwade** [comment]
Thanks Chris. So, TL;DR - we think the current data IS Correct - and that statistics.gov.uk is stale right? (Keeping up with CCG boundary changes is hellish).

**Comment by cblanc** [comment]
Yes, that's much hunch

Here you go: https://ons.maps.arcgis.com/home/item.html?id=7e76a3bcb0ad4826aba893d252a18c29
