### ISSUE TITLE
Nearest postcodes for postcode - not working on all postcodes

### ISSUE THREAD

**Issue by EdwardDunn** [ideal-postcodes/postcodes.io#168]
I am looking to use your API for a clients project. I am needing to get a list of all nearest postcodes for a specified postcode. I noticed when testing that it does not work for all instances.

Postcode - DD7 7TG , returns no nearest postcodes even though it is within a small town with multiple codes.

Hope this helps!

**Comment by cblanc** [comment]
Hi Edward

Thanks for the feedback. The issue here may be that the default radius (100m) does not cover another postcode - more likely to be the case in sparsely populated areas

Two solutions for this:

1. Increase the radius by appending a radius to the querystring (Max is 2000m). E.g.

```
https://postcodes.io/postcodes/DD77TG/nearest?radius=1000
```

2. For truly remote, middle-of-nowhere, postcodes, append widesearch=true to find the nearest beyond 2000. The tradeoff here is that you'll be able to retrieve a maximum of 10 postcodes

```
https://postcodes.io/postcodes/DD77TG/nearest?widesearch=true
```

**Comment by EdwardDunn** [comment]
@cblanc Thanks, that is exactly what i was looking for!
