### ISSUE TITLE
Wrong Admin Ward response in Slough Central

### ISSUE THREAD

**Issue by petrakuk** [ideal-postcodes/postcodes.io#169]
I've found a case in admin ward response for postcodes in Slough Central e.g SL1 1LN. 
Instead of "admin_ward": "Cental"  should be: "admin_ward": "Slough Central" response for all poscodes in Slough Central area.

**Comment by cblanc** [comment]
The GSS code for Central in Slough is `E05009339`

This appears to be correct according to data.gov.uk: http://statistics.data.gov.uk/doc/statistical-geography/E05009339

Also checking at source, `Ward names and codes UK as at 12_17.txt` provided alongside ONSPD this is the matching record:

```
E05009339	Central
```

I also checked other files in the ONSPD dataset and it appears twice more, both times as "Central"

```
./LAU2 names and codes UK as at 12_16 (NUTS).txt:5724:E05009339	Central

./LAU217_LAU117_NUTS315_NUTS215_NUTS115_DEC_UK_LU_NSPD.txt:5110:E05009339	Central	E06000039	Slough	UKJ11	Berkshire	UKJ1	Berkshire, Buckinghamshire and Oxfordshire	UKJ	South East (England)
```

I think Central may be the designated name of the ward, which admittedly is odd since `$Constituency Central` occurs 114 times in the district code dataset. [Example here](http://statistics.data.gov.uk/doc/statistical-geography/E05001355)

I'm a bit reticent to change it here, if upstream, the Government Statistical Service seem committed to calling it "Central" in this and other data sources. 

I'm afraid (pending changes upstream) this label may need to be used in conjunction with the `parliamentary_constituency` name to make sense

**Comment by petrakuk** [comment]
Clearly, thanks for an explanation.
