### ISSUE TITLE
outcode autocomplete

### ISSUE THREAD

**Issue by Supplantor** [ideal-postcodes/postcodes.io#186]
Is it possible to get an autocomplete feature for outcodes that returns a list of outcodes that start with the given input?

**Comment by cblanc** [comment]
Hi there,

I think if you wish to validate/complete outcodes it may be easier to just download the list of outcodes to the client. There are only ~3,000:

https://gist.github.com/cblanc/59305be0444205a312521635e5938477

The entire outcode list is 14kb (or 7kb gzipped). A `/postcodes?q=` query by contrast, which returns a maximum of 10 results, is 7kb in size (uncompressed)

Also would be much faster to query locally using some in memory data structure (rather than dispatch HTTP requests)... even a special purpose data structure is probably also overkill for such a small dataset. Few people would notice the performance gap with a naive O(n) implementation for autocomplete where n is so small

**Comment by Supplantor** [comment]
Ok, thanks for the tip I will look into this

**Comment by Sigmus** [comment]
Maybe this can also help you: https://github.com/krisk/Fuse depending on your use case.

**Comment by cblanc** [comment]
@Supplantor feel free to re-open if you get stuck
