### ISSUE TITLE
Postcode EC2M 2PG in London is returning 404

### ISSUE THREAD

**Issue by trettke** [ideal-postcodes/postcodes.io#199]
Thanks for the service! I'm using it on a booking app for baristas in London. One of the clients is trying to book with the postcode above but the service is throwing a 404. I've tested and I get a 404 with that valid postcode as well.

**Comment by cblanc** [comment]
Hi there,

EC2M 2PG was dropped in July 2014 (http://postcodes.io/terminated_postcodes/EC2M2PG)

There's a possibility it could have been added since the most recent ONSPD dataset was published in May 2018. However from what I can see on todays PAF dataset, Royal Mail have not reinstated this postcode since

**Comment by trettke** [comment]
Thanks for getting back to me so fast Chris. You're right, that postcode is no longer registered with Royal Mail. Although the business is registered at that address according to Google's API. But if you're using PAF as your source of truth you are right to have it marked as terminated.
