### ISSUE TITLE
Northern Ireland eastings and northings returning incorrectly.

### ISSUE THREAD

**Issue by seagerc** [ideal-postcodes/postcodes.io#287]
Alright, 

Been trying out the api recently but we have noticed that the eastings and northings are returning incorrect values on Northern Irish postcodes. 

For example BT11 9DT is returning the correct long and lat results but eastings and northings of an address found in wales. Due to system restrictions out of my hand i can't use long and lat.

Cheers.

**Comment by cblanc** [comment]
Have a feeling this might be because you're using OSGB grid system for Irish Northings/Eastings. Northern Ireland report their Northings/Eastings using the Irish Grid System. Try this: https://irish.gridreferencefinder.com/

**Comment by seagerc** [comment]
yea just after i made this comment i noticed the Irish grid ref finder was matching what we as getting back but was wondering if its possible to get what the normal grid reference site returns for the BT postcode?

**Comment by cblanc** [comment]
Since these are cartesian coordinates, I would assume it's a straightforward X,Y translation from the OSGB origin to the Irish one. Alternatively you could convert to WGS84 and then to OSGB. 

Either way, I'm not familiar with methods to do this or in which contexts these methods would be appropriate / accurate
