### ISSUE TITLE
App docker image fails to connnect to the DB image

### ISSUE THREAD

**Issue by kevinruscoe** [ideal-postcodes/postcodes.io#365]
I've installed docker on a Digital Ocean Ubuntu droplet (18.06) following the install docs at https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04

I've then installed the 2 docker containers and they're both running. If i go to http://{droplet-ip}:32769/random/postcodes it throws a 500 error.

Is there anything else I need to run, or any config options that need to be tweaked from the base images?

**Comment by cblanc** [comment]
Do you have any log data from the api container?

e.g. 
```
api_1  | {"level":50,"time":1563457746422,"pid":1,"hostname":"8747d980bf65","name":"postcodes.io","error":"connect ECONNREFUSED 172.19.0.2:5432","v":1}
```

**Comment by cblanc** [comment]
My hunch is that the database container hasn't fully ingested the dataset

The db image contains a zipped pg_dump. When postcodes.io.db is first built it will initiate a pg restore, which can take anywhere from 15s to 1 minute to complete. 

Was done this way because it makes the image 10x smaller than shipping an image with the pre-ingested

However the downside is there a period of unavailability

**Comment by kevinruscoe** [comment]
If I hit `docker logs ff3e09c5ad3e` (the db), the last thing printed is "database system is ready to accept connections" and I can see CREATE INDEX and postgis stuff. There doesn't appear to any errors.

As for the api container, I can see errors like "connect ECONNREFUSED 127.0.0.1:5432".

**Comment by kevinruscoe** [comment]
The service must be up, because if I map to ports 5432:5432, I can connect remotely to the Postgres server. I can even run queries, and they return results.

**Comment by kevinruscoe** [comment]
If I start the api container with POSTGRES_HOST={droplets ip}, it works fine.

I'm not a docker expert by any means, but I feel there's a command/option missing to allow the api to listen to the db.

**Comment by kevinruscoe** [comment]
`docker run -d --name db -e POSTGRES_USER=postcodesio -e POSTGRES_DB=postcodesiodb -e POSTGRES_PASSWORD=password idealpostcodes/postcodes.io.db`

A few differences here:

- I've added the `-d` flag to detach
- I've named the container 'db' with `--name db`

`docker run -d -p 80:8000 --link db -e POSTGRES_HOST=db idealpostcodes/postcodes.io`

Again, a few differences:

- I've used `--link db` to allow the api container access to the container named 'db'.
- I've used `-e POSTGRES_HOST=db` to tell the api container that the container named 'db' is the database host.

This seems to work with no issues on DO.

**Comment by cblanc** [comment]
[`--link` is a legacy feature](https://docs.docker.com/network/links/). These days you're expected to create a network. To connect the two containers, the missing steps are:
- Create a network
- Start the containers on the network
- Name the database container and pass it in in as POSTGRES_HOST on the api container

`docker-compose up` will do the above steps for you

At the time of writing, I left the configs open because there are a number of ways to network containers for different environments and different reasons to start a container.

I've noticed new users still use `--link` - perhaps it's easier to understand or there are a lot of out-of-date tutorials. You can also get the containers to bind to ports on localhost. Personally, a lot of the time, I just want to stand up the pg container and psql into 5432. Myself and [others](https://github.com/Unmortgage/postcodes-io-helm-chart) have put this project onto kubernetes which has its own multitudinous ways of networking containers with pods and services.

If users are spending time mired in docker, then the install instructions have failed. So with regards to the documentation, I'm a bit more inclined to put `docker-compose up` front and centre like in the readme and making a note on networks if users are committed to doing things from scratch.

**Comment by kevinruscoe** [comment]
Yeah, I noticed that the --link was deprecated.

So, a TL;DR, clone the repo and run `docker-compose up -d` rather than trying to run the containers on their own.

**Comment by cblanc** [comment]
Yes, in this particular use case it is
