### ISSUE TITLE
Postcode Contribution

### ISSUE THREAD

**Issue by caleuanhopkins** [ideal-postcodes/postcodes.io#40]
Can you let us know how we can contribute postcode data? A number of postcode areas for Scotland/Aberdeen are missing and I'd like to help fill in this gap.

Thanks

**Comment by cblanc** [comment]
Could you give an example of missing postcode areas to investigate?

Thanks

**Comment by caleuanhopkins** [comment]
hmm looks like maybe our data source is feeding us incorrect postcodes.

Interest still stands, is there any process in place for contributing post codes?

**Comment by cblanc** [comment]
Right now, postcodes.io pulls from ONS' Postcode Directory. They in turn retrieve postcode information from Royal Mail every 3 months. Ultimately it's Royal Mail who arbitrarily decide what happens to the national postcode infrastructure.

Currently, if there is a missing postcode (or outcode) the likely explanations are:
1) The postcode is extremely new. It still needs time to filter down to ONS' Postcode Directory from Royal Mail. Typically the maximum lag time is 3 months
2) The postcode has been deprecated. Royal Mail has decommissioned the postcode for whatever reason. Unfortunately a lot of address stores do not update these postcodes, so dead postcodes can hang around for a while
3) There's a bug in the postcodes.io scripts which import postcode data

Since we're already getting it from the 'horses mouth', I don't think it's necessary right now to put in place a process to contribute, curate and verify postcodes. For the time being, I feel it's probably better to keep postcodes.io as authoritative as possible even if the postcode list can be up to 90 days stale.

**Comment by caleuanhopkins** [comment]
The process as it stand just now, seems effective. My only worry is that Royal Mail is no longer a public service and or the longevity of the API, pulling data from technically a private company worries me slightly. However, I think I'm seeing a bit further into a scenario which can only be described at the this point as possible but not fully plausible. 

It would be nice to keep this issue open incase the feed of postcodes ever becomes "questionable". For now, I think your flow is probably the most effective automated flow.

**Comment by cblanc** [comment]
I share those concerns as well. Will leave this issue up for the time being

**Comment by stasparshin** [comment]
Hi,
As far as I understand the whole [PA area](https://en.wikipedia.org/wiki/PA_postcode_area) isn't covered. 
Will somebody please check this?

**Comment by cblanc** [comment]
Hi there, you can run a prefix search to confirm. But it seems postcodes in the PA* outward area is returned

```
api.postcodes.io/postcodes?q=pa
```

**Comment by stasparshin** [comment]
So the issue is rather with my particular PA427NY. Is it possible that this zip is new and it isn't in the Royal Mail db yet?

**Comment by cblanc** [comment]
Sometimes, it may be that it's a decommissioned postcode. Alternatively, it may be new and yet to make it into ONSPD (since it's updated quarterly). It's more often the former 

However for this particular postcode, based on my own sources, I don't think it exists or has existed in the past. Perhaps there's a typo in there?

**Comment by stasparshin** [comment]
That was a typo indeed. Sorry for wasting you time.

**Comment by cblanc** [comment]
No worries. No time was wasted
