### ISSUE TITLE
Question: Co-ordinate decimal places

### ISSUE THREAD

**Issue by corkybeta** [ideal-postcodes/postcodes.io#418]
postcodes.io normally returns latitude and longitude to 6 decimal places (or fewer, such as NR14 7PZ). Postcoder.com returns 10 decimal places. The application I am using this data for can only accept co-ordinates up to 6 decimal places. Will postcodes.io ever return more accurate co-ordinates in future? I cannot see anything in the documentation specifying fixed accuracy, and also can't see which source of data leads to Postcoder having different results (unless you already round to 6 d.p.)

**Comment by cblanc** [comment]
Hi there

I believe the coordinates are [extracted as they are reported by ONSPD](https://github.com/ideal-postcodes/postcodes.io/blob/a398dbb845dfbf37952bd9fa25abb18ea001a2e2/app/models/postcode.js#L698)

However I don't know:

1. Enough about postgresql to predict if it will consistently return [double precision](https://www.postgresql.org/docs/12/datatype-numeric.html) data types based on the input precision across different systems/environments. I suspect it will be consistent, but I can't be certain
2. Whether ONS will start reporting more DPs in the future whether by design or accident

If you do require fixed values, perhaps Northings/Eastings would be better? Each value can be up to 6 digits. It's also possible to reasonably [convert it into a geolocation](https://github.com/ideal-postcodes/ospoint) and fix the decimal places of the result

Truncating at the 6th DP shouldn't make much of a difference. I think it's a ~10cm difference or so
