### ISSUE TITLE
Jersey island doesn't contain post codes

### ISSUE THREAD

**Issue by tommy7600** [ideal-postcodes/postcodes.io#42]
Jersey island (mainly all islands) doesn't contain post codes

**Comment by cblanc** [comment]
The ONSPD does contain island postcode data however you won't be able to find these by doing a geolocation search since it doesn't contain the location data for these postcodes.

There was a similar issue on a different project which uses ONSPD: https://github.com/theodi/uk-postcodes/issues/37

If there's an authoritative and openly licensed source for this data, I'd be happy to integrate it.
