### ISSUE TITLE
Is it possible to specify an area and get a random postcode for that area?

### ISSUE THREAD

**Issue by andrewcartwright1** [ideal-postcodes/postcodes.io#46]
HI,

Was just wondering if it's possible to do this already - This site allows you to specify an area to generate a random postcode or leave it blank to generate a random one - http://www.doogal.co.uk/PostcodeGenerator.php

Was just wondering if this api has the ability to do that? Or if it could possibly be added?

Many thanks!

**Comment by cblanc** [comment]
This looks like something I'd like to incorporate. But the tricky part is finding a way to make this fast. 

Random row lookups in postgres are expensive as the simple solutions involve `COUNT` or `OFFSET`. In fact we had to disable random postcode lookups for a few weeks because it was taking postgres too long to complete these queries. Currently we make /random/postcodes fast by first loading ID's into memory and then picking a random number.

It could be that a query narrowed down by area will be small enough to traverse quickly. If not, we may need to look at some in memory data structure to speed things up.

**Comment by cblanc** [comment]
You can query for random postcodes within an outcode with /random/postcodes?outcode=:outcode

The update has just been pushed to a new server to avoid any downtime for data migrations. It could mean you wont see the change until your DNS cache clears, which should be quite quick in any case.

**Comment by andrewcartwright1** [comment]
Awesome, thank you very much!
