### ISSUE TITLE
Add postcodes found on the web interface but not the API

### ISSUE THREAD

**Issue by madelinekosse** [ideal-postcodes/postcodes.io#535]
I have been using the POST /postcodes endpoint to fetch location data and found that some are returned as nil. The only ones I noticed begin with NP7 1B- but there may be others. Here is an example request and response that I received that illustrates the problem:

Request:
```
 https://api.postcodes.io/postcodes
	 -H "Content-Type: application/json" 
     -H "Accept: application/json" 
     -d "{\"postcodes\":[\"NP7 1BJ\"]}"
```
response:
```
{
    "status": 200,
    "result": [{
        "query": "NP7 1BJ",
        "result": null
    }]
}
```

When I looked this postcode up on the web interface (https://postcodes.io/explore?) the location was found correctly, so the data must be available somewhere.

**Comment by cblanc** [comment]
Hi @madelinekosse 

I had a look at that particular postcode. Seems to have been removed in [Dec 2018](http://postcodes.io/terminated_postcodes/NP7%201BJ)

Am also having trouble retrieving it on postcodes.io/explore or the single postcode search `/postcode/:postcode`

Are you using the public API exclusively or running the docker database image? Since it was recently expired, some older releases of that image would be returning results for NP71BJ
