### ISSUE TITLE
OSGR? 

### ISSUE THREAD

**Issue by dbrb2** [ideal-postcodes/postcodes.io#55]
Not sure if there would be any other people who would find this useful, but you never know...
The data returned by the API already contains Eastings and Northings.

It is not hard from this to calculate the OSGR (for instance TQ 317 801), but it would be lovely not to have to do even that calculation! 

In this case since each OS grid square is 100km, and TQ is 5 squares in, 1 up, than maps to 531700E, 180100N

**Comment by cblanc** [comment]
Is there a reference you can point me to which details the conversion process?

This is the first request I've seen to incorporate OSGR. I'm in two minds about incorporating it without more people asking for it to be include. I'd be happy to include a reference in the documentation however if someone would like to derive it from Northings/Eastings. 

I have a feeling that since most people are accessing the API programmatically, it should be pretty straightforward to add an extra step to retrieve OSGR.

**Comment by dbrb2** [comment]
The library I use for the conversion lives here:

https://github.com/dvdoug/PHPCoord

Which tbh does make a conversion very simple:

$os = new OSRef($eastings, $northings);
$osgr=$os->toSixFigureString();

In terms of what is actually going on under the bonnet, this page explains
it quite well:

http://www.movable-type.co.uk/scripts/latlong-gridref.html

The only slightly strange part in the conversion is working out which
letter pair represents the grid square in question. The workings of this
can be seen in the library above here:

https://github.com/dvdoug/PHPCoord/blob/master/OSRef.php

Starting on line 64
