### ISSUE TITLE
Inconsistent response when there are two "nearest" postcodes

### ISSUE THREAD

**Issue by goggelj** [ideal-postcodes/postcodes.io#70]
Hi there,

Identified the above issue when using the following as an input:
{"lat":53.480412,"long":-2.223332}

Output 1: M4 6DN
"longitude": -2.2234081205581,
"latitude": 53.4804876316574,

Output 2: M4 6DT
"longitude": -2.2234081205581,
"latitude": 53.4804876316574,

While both are valid, the response from the server is inconsistent as sometimes I get the former and sometimes I get the latter as the first element in the list.

Is there something I can do on my side to ensure the response is consistent? Is it an issue on your side?

Jonathan

**Comment by cblanc** [comment]
The issue can be fixed server side. I've just pushed an update which will sort on postcode if they share the same geolocation

This particular issue probably only emerged within the last month when we moved to use multiple postgresql instances to split the load. It seems that one instance will return a consistent order. However this order would vary across instances causing your results to vary slightly with each request due to load balancing
