### ISSUE TITLE
Finding all Postcodes within X distance.

### ISSUE THREAD

**Issue by xitude** [ideal-postcodes/postcodes.io#74]
I'd love a way to find all the postcodes within a **X** distance.

`api.postcodes.io/postcodes/:postcode/within/:value`

**Comment by cblanc** [comment]
Would `https://api.postcodes.io/postcodes/:postcode/nearest` suffice? This returns nearest postcodes for a particular postcode ordered by distance

You can set the distance using `radius=` in the querystring, this is 100m by default and capped at 2,000m 

There's also a `limit=` parameter which controls the number of results to return. Default is 10, maximum is 100

I'm afraid it's not really feasible to return *all* the postcodes, since in urban areas this would be a very expensive operation returning MBs of data. If you're after *all* the postcodes, it may be better to query a local copy of our database directly

Link to pg_dump is available here: https://github.com/ideal-postcodes/postcodes.io/blob/master/latest

If you're not sure how to query for geolocations with Postgresql + PostGIS, here's where the logic for finding nearby postcodes is handled: https://github.com/ideal-postcodes/postcodes.io/blob/master/app/models/postcode.js#L278

It's a good starting point to finding out how it works

**Comment by xitude** [comment]
@cblanc Perfect. I didn't know a dump was available. Does it get updated regularly?

**Comment by cblanc** [comment]
Every 3 months shortly after the quarterly updates are released, latest is May 2016

**Comment by noman1658** [comment]
hy

**Comment by noman1658** [comment]
anyone there?
